version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis-test
      CELERY_BROKER_URL: redis://redis-test:6379/1
      CELERY_RESULT_BACKEND: redis://redis-test:6379/1
      REDIS_DB: 1
      PYTHONPATH: /app
      APP_MODULE: app.main:app
    depends_on:
      - redis-test
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    networks:
      - test-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      REDIS_HOST: redis-test
      CELERY_BROKER_URL: redis://redis-test:6379/1
      CELERY_RESULT_BACKEND: redis://redis-test:6379/1
      REDIS_DB: 1
      PYTHONPATH: /app
    depends_on:
      - redis-test
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    networks:
      - test-network
    command: ["pytest", "--cov=app", "tests/"]

  redis-test:
    image: redis:alpine
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 