version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run pytest --cov=app tests/
    environment:
      REDIS_HOST: redis-test
      CELERY_BROKER_URL: redis://redis-test:6379/1
      CELERY_RESULT_BACKEND: redis://redis-test:6379/1
      REDIS_DB: 1
    depends_on:
      - redis-test
    volumes:
      - .:/app
    networks:
      - test-network

  redis-test:
    image: redis:alpine
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 